#define MILLISECONDS_PER_SECOND 1000
#define NANOSECONDS_PER_MILLISECOND 1000000

#define BYTES_PER_SAMPLE 4
#define SAMPLES_PER_SECOND 6000
#define SAMPLE_LEN_MILLISECONDS 50
#define SAMPLE_LEN BYTES_PER_SAMPLE * SAMPLES_PER_SECOND * SAMPLE_LEN_MILLISECONDS / MILLISECONDS_PER_SECOND

#define SAMPLE_COMMUNICATION_LEN = SAMPLE_LEN + 1
#define FULL_SAMPLE_LEN = SAMPLE_COMMUNICATION_LEN + 1

#define AUDIO_TIME SAMPLE_LEN_MILLISECONDS * NANOSECONDS_PER_MILLISECOND
#define SPACIAL_TIME 1000000000

#define audio_char 'A'
#define space_char 'S'

void printBinary(int num);